"""Initial schema

Revision ID: a4ea1226660c
Revises: 
Create Date: 2025-11-22 18:25:14.470100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4ea1226660c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tier_restriction', postgresql.ENUM('NONE', 'PRO_ONLY', 'ENTERPRISE_ONLY', name='credit_tier_restriction'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits >= 0', name='ck_credit_packages_credits'),
    sa.CheckConstraint('price_usd >= 0', name='ck_credit_packages_price'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_packages_active', 'credit_packages', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('tier', postgresql.ENUM('FREE', 'PRO', 'ENTERPRISE', name='user_tier'), nullable=False),
    sa.Column('credit_balance', sa.BigInteger(), nullable=False),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('dataset_count', sa.Integer(), nullable=False),
    sa.Column('workflow_count', sa.Integer(), nullable=False),
    sa.Column('model_count', sa.Integer(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credit_balance >= 0', name='ck_users_credit_balance'),
    sa.CheckConstraint('dataset_count >= 0', name='ck_users_dataset_count'),
    sa.CheckConstraint('model_count >= 0', name='ck_users_model_count'),
    sa.CheckConstraint('storage_used_bytes >= 0', name='ck_users_storage'),
    sa.CheckConstraint('streak_count >= 0', name='ck_users_streak_count'),
    sa.CheckConstraint('workflow_count >= 0', name='ck_users_workflow_count'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_tier', 'users', ['tier'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('original_format', postgresql.ENUM('CSV', 'JSON', 'PARQUET', 'EXCEL', 'UNKNOWN', name='file_format'), nullable=True),
    sa.Column('original_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('s3_path', sa.Text(), nullable=True),
    sa.Column('parquet_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('columns_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('problem_type', postgresql.ENUM('CLASSIFICATION', 'REGRESSION', 'CLUSTERING', 'OTHER', name='problem_type'), nullable=True),
    sa.Column('target_column', sa.Text(), nullable=True),
    sa.Column('is_sample_dataset', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('column_count >= 0', name='ck_datasets_column_count'),
    sa.CheckConstraint('original_size_bytes >= 0', name='ck_datasets_original_size'),
    sa.CheckConstraint('parquet_size_bytes >= 0', name='ck_datasets_parquet_size'),
    sa.CheckConstraint('row_count >= 0', name='ck_datasets_row_count'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='ux_datasets_userid_name')
    )
    op.create_index('idx_datasets_created_at', 'datasets', ['created_at'], unique=False)
    op.create_index('idx_datasets_is_sample', 'datasets', ['is_sample_dataset'], unique=False)
    op.create_index('idx_datasets_user_id', 'datasets', ['user_id'], unique=False)
    op.create_table('tutorials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='tutorial_difficulty'), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('enrollment_count', sa.Integer(), nullable=False),
    sa.Column('completion_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completion_count >= 0', name='ck_tutorials_completion'),
    sa.CheckConstraint('enrollment_count >= 0', name='ck_tutorials_enrollment'),
    sa.CheckConstraint('estimated_duration_minutes >= 0', name='ck_tutorials_duration'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tutorials_author', 'tutorials', ['created_by_user_id'], unique=False)
    op.create_index('idx_tutorials_difficulty', 'tutorials', ['difficulty'], unique=False)
    op.create_index('idx_tutorials_is_featured', 'tutorials', ['is_featured'], unique=False)
    op.create_index('idx_tutorials_is_published', 'tutorials', ['is_published'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('graph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflows_last_modified', 'workflows', ['last_modified'], unique=False)
    op.create_index('idx_workflows_user_id', 'workflows', ['user_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_experiments_dataset_id', 'experiments', ['dataset_id'], unique=False)
    op.create_index('idx_experiments_user_id', 'experiments', ['user_id'], unique=False)
    op.create_table('user_tutorial_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tutorial_id', sa.UUID(), nullable=False),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('completed_steps', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completion_percentage >= 0 AND completion_percentage <= 100', name='ck_user_tutorial_progress_percentage'),
    sa.CheckConstraint('current_step_index >= 0', name='ck_user_tutorial_progress_step'),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tutorial_id', name='ux_user_tutorial')
    )
    op.create_index('idx_user_tutorial_progress_last_accessed', 'user_tutorial_progress', ['last_accessed_at'], unique=False)
    op.create_index('idx_user_tutorial_progress_tutorial_id', 'user_tutorial_progress', ['tutorial_id'], unique=False)
    op.create_index('idx_user_tutorial_progress_user_id', 'user_tutorial_progress', ['user_id'], unique=False)
    op.create_table('workflow_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('graph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_snapshots_user_id', 'workflow_snapshots', ['user_id'], unique=False)
    op.create_index('idx_workflow_snapshots_workflow_id', 'workflow_snapshots', ['workflow_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workflow_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'QUEUED', 'RUNNING', 'FAILED', 'COMPLETED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('credits_cost', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits_cost >= 0', name='ck_jobs_credits_cost'),
    sa.CheckConstraint('duration_seconds >= 0', name='ck_jobs_duration'),
    sa.CheckConstraint('priority >= 0', name='ck_jobs_priority'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_snapshot_id'], ['workflow_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_celery_task_id', 'jobs', ['celery_task_id'], unique=False)
    op.create_index('idx_jobs_queue', 'jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('idx_jobs_user_id', 'jobs', ['user_id'], unique=False)
    op.create_index('idx_jobs_workflow_snapshot_id', 'jobs', ['workflow_snapshot_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('PURCHASE', 'CONSUMPTION', 'REFUND', 'ADJUSTMENT', name='transaction_type'), nullable=False),
    sa.Column('related_job_id', sa.UUID(), nullable=True),
    sa.Column('related_purchase_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_tx_created_at', 'credit_transactions', ['created_at'], unique=False)
    op.create_index('idx_credit_tx_job_id', 'credit_transactions', ['related_job_id'], unique=False)
    op.create_index('idx_credit_tx_type', 'credit_transactions', ['transaction_type'], unique=False)
    op.create_index('idx_credit_tx_user_id', 'credit_transactions', ['user_id'], unique=False)
    op.create_table('job_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('node_type', postgresql.ENUM('DATASET', 'PREPROCESS', 'MODEL', 'VISUALIZE', 'SAVE', name='node_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', name='node_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds >= 0', name='ck_job_nodes_duration'),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name='ck_job_nodes_progress'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'node_id', name='ux_jobnode_jobid_nodeid')
    )
    op.create_index('idx_job_nodes_job_id', 'job_nodes', ['job_id'], unique=False)
    op.create_index('idx_job_nodes_status', 'job_nodes', ['status'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('job_node_id', sa.UUID(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('parent_model_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('model_type', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('s3_model_path', sa.Text(), nullable=True),
    sa.Column('model_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hyperparameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shap_plots_s3_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mlflow_run_id', sa.Text(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('model_size_bytes >= 0', name='ck_models_size'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_node_id'], ['job_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_models_created_at', 'models', ['created_at'], unique=False)
    op.create_index('idx_models_dataset_id', 'models', ['dataset_id'], unique=False)
    op.create_index('idx_models_is_production', 'models', ['is_production'], unique=False)
    op.create_index('idx_models_job_id', 'models', ['job_id'], unique=False)
    op.create_index('idx_models_name', 'models', ['name'], unique=False)
    op.create_index('idx_models_parent_model_id', 'models', ['parent_model_id'], unique=False)
    op.create_index('idx_models_user_id', 'models', ['user_id'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'job_id', name='ux_experiment_runs_experiment_job')
    )
    op.create_index('idx_experiment_runs_experiment_id', 'experiment_runs', ['experiment_id'], unique=False)
    op.create_index('idx_experiment_runs_job_id', 'experiment_runs', ['job_id'], unique=False)
    op.create_index('idx_experiment_runs_model_id', 'experiment_runs', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_experiment_runs_model_id', table_name='experiment_runs')
    op.drop_index('idx_experiment_runs_job_id', table_name='experiment_runs')
    op.drop_index('idx_experiment_runs_experiment_id', table_name='experiment_runs')
    op.drop_table('experiment_runs')
    op.drop_index('idx_models_user_id', table_name='models')
    op.drop_index('idx_models_parent_model_id', table_name='models')
    op.drop_index('idx_models_name', table_name='models')
    op.drop_index('idx_models_job_id', table_name='models')
    op.drop_index('idx_models_is_production', table_name='models')
    op.drop_index('idx_models_dataset_id', table_name='models')
    op.drop_index('idx_models_created_at', table_name='models')
    op.drop_table('models')
    op.drop_index('idx_job_nodes_status', table_name='job_nodes')
    op.drop_index('idx_job_nodes_job_id', table_name='job_nodes')
    op.drop_table('job_nodes')
    op.drop_index('idx_credit_tx_user_id', table_name='credit_transactions')
    op.drop_index('idx_credit_tx_type', table_name='credit_transactions')
    op.drop_index('idx_credit_tx_job_id', table_name='credit_transactions')
    op.drop_index('idx_credit_tx_created_at', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('idx_jobs_workflow_snapshot_id', table_name='jobs')
    op.drop_index('idx_jobs_user_id', table_name='jobs')
    op.drop_index('idx_jobs_queue', table_name='jobs')
    op.drop_index('idx_jobs_celery_task_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_workflow_snapshots_workflow_id', table_name='workflow_snapshots')
    op.drop_index('idx_workflow_snapshots_user_id', table_name='workflow_snapshots')
    op.drop_table('workflow_snapshots')
    op.drop_index('idx_user_tutorial_progress_user_id', table_name='user_tutorial_progress')
    op.drop_index('idx_user_tutorial_progress_tutorial_id', table_name='user_tutorial_progress')
    op.drop_index('idx_user_tutorial_progress_last_accessed', table_name='user_tutorial_progress')
    op.drop_table('user_tutorial_progress')
    op.drop_index('idx_experiments_user_id', table_name='experiments')
    op.drop_index('idx_experiments_dataset_id', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('idx_workflows_user_id', table_name='workflows')
    op.drop_index('idx_workflows_last_modified', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('idx_tutorials_is_published', table_name='tutorials')
    op.drop_index('idx_tutorials_is_featured', table_name='tutorials')
    op.drop_index('idx_tutorials_difficulty', table_name='tutorials')
    op.drop_index('idx_tutorials_author', table_name='tutorials')
    op.drop_table('tutorials')
    op.drop_index('idx_datasets_user_id', table_name='datasets')
    op.drop_index('idx_datasets_is_sample', table_name='datasets')
    op.drop_index('idx_datasets_created_at', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('idx_users_tier', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_credit_packages_active', table_name='credit_packages')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
